# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: cycleassembler-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
  - biobuilds

dependencies:
  - conda-forge::python=3.8.0
  - bioconda::trim-galore=0.6.6
  - bioconda::bbmap=38.90
  - bioconda::vsearch=2.15.2
  - bioconda::nextgenmap=0.5.5
  - bioconda::samtools=1.11
  - bioconda::fastp=0.20.1
  - bioconda::spades=3.15.0
  - bioconda::seqtk=1.3
  - bioconda::muscle=3.8.1551
  - bioconda::reaper=16.098
  - biobuilds::fasta=36.3.8e




